export const GET_RECORDS = 'GET_RECORDS';
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS';
export const GET_RECORD = 'GET_RECORD';
export const POST_RECORD = 'POST_RECORD';
export const POST_RECORD_SUCCESS = 'POST_RECORD_SUCCESS';
export const PUT_RECORD = 'PUT_RECORD';
export const DELETE_RECORD = 'DELETE_RECORD';
