export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS';
export const GET_RECORD_SUCCESS = 'GET_RECORD_SUCCESS';
export const POST_RECORD_SUCCESS = 'POST_RECORD_SUCCESS';
export const PUT_RECORD_SUCCESS = 'PUT_RECORD_SUCCESS';
export const DELETE_RECORD_SUCCESS = 'DELETE_RECORD_SUCCESS';
